---
- hosts: all
  tasks:
    - name: Run bindep role
      include_role:
        name: bindep

    - name: Ensure tox
      include_role:
        name: ensure-tox

    - name: Run revoke-sudo role
      include_role:
        name: revoke-sudo
