---

- hosts: all
  tasks:
    - name: Add Docker GPG key.
      rpm_key:
        key: https://download.docker.com/linux/centos/gpg
        state: present

    - name: Fetch Docker CentOS Repository
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
        owner: root
        group: root
        mode: 0644

    - name: Install IUS repository
      yum:
        name: https://centos7.iuscommunity.org/ius-release.rpm
        state: present

    - name: Add Nodesource repositories for Node.js (CentOS 7+).
      yum:
        name: https://rpm.nodesource.com/pub_8.x/el/7/x86_64/nodesource-release-el7-1.noarch.rpm
        state: present

    - name: Install Docker, python, and toolchain packages
      package:
        name: "{{ item }}"
        state: present
      with_items: ['docker-ce', 'python-pip', 'python-devel',
                   'python36u', 'python36u-pip', 'python36u-devel',
                   'gcc', 'gcc-c++', 'make', 'python-devel', 'openldap-devel',
                   'git', 'bzip2', 'fontconfig', 'fontconfig-devel', 'curl', 'curl-devel',
                   'openssl-devel']

    - name: Install libs for headless ui testing
      package:
        name: "{{ item }}"
        state: present
      with_items: ['pango', 'libXcomposite', 'libXcursor', 'libXdamage', 'libXext', 'libXi', 'libXtst',
                   'cups-libs', 'libXScrnSaver', 'libXrandr', 'GConf2', 'alsa-lib', 'atk', 'gtk3',
                   'ipa-gothic-fonts', 'xorg-x11-fonts-100dpi', 'xorg-x11-fonts-75dpi', 'xorg-x11-utils',
                   'xorg-x11-fonts-cyrillic', 'xorg-x11-fonts-Type1', 'xorg-x11-fonts-misc']

    - name: Install NodeJS and temporarily disable epel
      yum:
        name: nodejs
        disablerepo: epel

    - name: Install Grunt from npm
      npm:
        name: grunt
        global: yes
        state: present

    - name: Ensure Docker is started and enabled at boot.
      service:
        name: docker
        state: started
        enabled: yes

    - name: Ensure docker users are added to the docker group.
      user:
        name: "{{ item }}"
        groups: docker
        append: true
      with_items: ['zuul']

    - name: Install wheel first
      pip:
        name: 'wheel'

    - name: Install some python packages
      pip:
        name: "{{ item }}"
      with_items: ['docker-compose', 'tox', 'pipenv', 'boto', 'boto3']

    - name: Install some python3 packages
      pip:
        name: "{{ item }}"
        executable: "pip3.6"
      with_items: ["flake8", "virtualenv"]

    - name: Symlink python 3.6 to python3
      file:
        src: /usr/bin/python3.6
        dest: /usr/bin/python3
        owner: root
        group: root
        state: link

      # https://success.docker.com/article/ipv4-forwarding
      # PR's that invoked Zuul were failing on tox command.
      # sshed to the GCE static node and ran the tox command manually.
      # On the docker build step, the below error was seen. This caused the yum
      # install to fail. The below command fixes this.
      # Step 4/40 : RUN mkdir /tmp/requirements
      #  ---> [Warning] IPv4 forwarding is disabled. Networking will not work.
      #  ---> Running in 0ff7a77d106d
      # Removing intermediate container 0ff7a77d106d
      #  ---> 725155375db4
      # Step 5/40 : RUN yum -y update && yum -y install curl epel-release && yum -y install https://centos7.iuscommunity.org/ius-release.rpm
      #  ---> [Warning] IPv4 forwarding is disabled. Networking will not work.
    - name: UCP requires IPv4 IP Forwarding
      sysctl:
        name: "net.ipv4.conf.all.forwarding"
        value: 1
        sysctl_set: yes
        state: present

    - name: Remove sudo-group access on GCE host from the Zuul user
      command: "gpasswd -d zuul {{ item }}"
      with_items: ['google-sudoers', 'adm']
      register: remove_sudo
      failed_when: |
        remove_sudo is not success and 'not a member' not in remove_sudo.stderr
