---
- hosts: localhost
  roles:
    - role: add-fileserver
      fileserver: "{{ site_ansiblelogs }}"
    - emit-ara-html

- hosts: "{{ site_ansiblelogs.fqdn }}"
  tasks:
    # Use a block because play vars doesn't take precedence on roles vars
    - block:
        - import_role: name=upload-logs
      vars:
        zuul_log_url: "{{ site_ansiblelogs.url }}"
        zuul_logserver_root: "{{ site_ansiblelogs.path }}"

- hosts: localhost
  ignore_errors: yes
  roles:
    - role: submit-logstash-jobs
      logstash_gearman_server: "ansible.softwarefactory-project.io"
      logstash_gearman_server_port: 4731
