# Set optin to False to disable log-classify
logclassify_optin: True
# Set report to True to hijack the reported log url
logclassify_report: False

# How many job logs to use for building the model
logclassify_model_job_count: 2
# The pipeline to use for building the model
logclassify_model_pipeline:

# Anomaly distance threshold (between 0.0 and 1.0)
logclassify_threshold: 0.2
# Context to include
logclassify_before_context: 3
logclassify_after_context: 2

# How old (in days) can a built model be
logclassify_model_age: 7
# Build a model per project (instead of per job)
logclassify_model_per_project: false

logclassify_static_location: /static
logclassify_model_store_url: https://softwarefactory-project.io/logs/classifiers
logclassify_zuul_web: https://softwarefactory-project.io/zuul/api/tenant/local
logclassify_tmp_dir: /tmp/log-classify
logclassify_model_dir: "{{ logclassify_tmp_dir }}"

# Process console-log
logclassify_console: true

# Include paths from baseline logs
logclassify_logserver_dir: ""
# Location of test instances logs that match the above include_paths
logclassify_local_dir: ""
# For example, devstack job may uses:
#  logclassify_logserver_dir: controller/logs/
#  logclassify_local_dir: /opt/stack/logs/

# Exclude regexp list of path
logclassify_exclude_paths: []
# Exclude regexp list of basenames
logclassify_exclude_files: []

# Enable log-classify --debug
logclassify_debug: false


logclassify_max_run_time: 900
