---
- name: Set IPv4 nameservers
  set_fact:
    unbound_primary_nameserver: '{{ unbound_primary_nameserver_v4 }}'
    unbound_secondary_nameserver: '{{ unbound_secondary_nameserver_v4 }}'

- name: Include OS-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yaml"
    - "{{ ansible_os_family }}.yaml"
    - "default.yaml"

- name: Ensure Unbound conf.d directory exists
  become: true
  file:
    path: "{{ unbound_confd }}"
    state: directory

- name: Configure unbound forwarding
  become: true
  template:
    dest: "{{ unbound_confd }}/forwarding.conf"
    owner: root
    group: root
    mode: 0644
    src: forwarding.conf.j2
  notify:
    - Restart unbound

- name: Configure unbound TTL
  become: true
  template:
    dest: "{{ unbound_confd }}/ttl.conf"
    owner: root
    group: root
    mode: 0644
    src: ttl.conf.j2
  notify:
    - Restart unbound

- name: Update resolv.conf to localhost
  become: true
  copy:
    content: nameserver 127.0.0.1
    dest: /etc/resolv.conf

- name: Start unbound
  become: true
  service:
    name: unbound
    state: started
    enabled: true
