---
- name: Calculate required swap
  set_fact:
    swap_required: "{{ configure_swap_size - configure_swap_current_total | int }}"

- block:
    - name: Get root filesystem
      shell: df --output='fstype' /root | tail -1
      register: root_fs

    - name: Save root filesystem
      set_fact:
        root_filesystem: "{{ root_fs.stdout }}"

# Note, we don't use a sparse device to avoid wedging when disk space
# and memory are both unavailable.

- name: Create swap backing file
  become: true
  command: dd if=/dev/zero of=/root/swapfile bs=1M count={{ swap_required }}
  args:
    creates: /root/swapfile

- name: Ensure swapfile perms
  become: true
  file:
    path: /root/swapfile
    owner: root
    group: root
    mode: 0600

- name: Make swapfile
  become: true
  command: mkswap /root/swapfile

- name: Write swap to fstab
  become: true
  mount:
    path: none
    src: /root/swapfile
    fstype: swap
    opts: sw
    passno: 0
    dump: 0
    state: present

- name: Add all swap
  become: true
  command: swapon -a
