- hosts: localhost
  tasks:
    - name: Run emit-job-header role
      include_role:
        name: emit-job-header
      var:
        zuul_log_url: http://ansible.softwarefactory-project.io/logs

    - name: Run log-inventory role
      include_role:
        name: log-inventory

- hosts: all
  gather_facts: no
  tasks:
    - name: Run prepare-workspace role
      include_role:
        name: prepare-workspace

    - name: Run validate-host role
      include_role:
        name: validate-host
